services:
  app:
    build: .
    container_name: llm-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./templates:/app/templates
    depends_on:
      - db

  db:
    image: alpine
    container_name: dummy-db
    environment:
      - DB_HOST=$(DB_HOST)
      - DB_PORT=$(DB_PORT)
      - DB_USER=$(DB_USER)
      - DB_PASSWORD=$(DB_PASSWORD)
      - DB_NAME=$(DB_NAME)
